### ISSUE TITLE
Background and font in black color if no langage detected

### ISSUE THREAD

**Issue by gaelalso** [kenlog/HighlightCodeSyntax#1]
We use code insert to paste log file and not code character, so i think it's the reason why your plugin make all characters on black (font and background), but it's this case, we cannot read anything.
`LOG TEX
TES1:DDDDDD
TEST2:WWWWW
INFO1:DDDDD
INFO2 ://///////
`

**Comment by kenlog** [comment]
Hello @gaelalso to help you solve, I need more information. It could probably be a style sheet, which overwrites the classes of this module.  Show me a screen image that does not display correctly, even the list of installed plugins can be used to highlight conflicts.

**Comment by kenlog** [comment]
Hi @gaelalso I am waiting for an answer, otherwise I close the issue.

**Comment by gaelalso** [comment]
Sorry for delay 
<img width="985" alt="CODE BLACK BLACK" src="https://user-images.githubusercontent.com/41582236/55828209-2f21f300-5b0c-11e9-8ec4-7b98e246a5a2.PNG">

**Comment by kenlog** [comment]
Hi @gaelalso try entering **```bash** you should get this
![log](https://user-images.githubusercontent.com/11728231/55864475-db032700-5b7c-11e9-8cff-32f00923a35f.png)

**Comment by kenlog** [comment]
Hi @gaelalso have you got to check?

**Comment by kenlog** [comment]
@gaelalso there are news? :cactus:

**Comment by gaelalso** [comment]
I'm in travel. I can return you a feedback next week. Thanks you to your
survey

Le mar. 16 avr. 2019 à 19:01, Valentino Pesce <notifications@github.com> a
écrit :

**Comment by kenlog** [comment]
@gaelalso I kindly ask you to give me an answer, otherwise I consider the issue closed.

**Comment by gaelalso** [comment]
It's good yes. Thanks you
