### ISSUE TITLE
Background too dark

### ISSUE THREAD

**Issue by arocholl** [kenlog/HighlightCodeSyntax#2]
### Thanks for your contribution, it works great. However, the background is too dark for normal text which display in light gray, not white, so it is hard to read. Could it be possible to adjust colors, at least background color?
![hardtoread](https://user-images.githubusercontent.com/695504/57520713-9d7def00-731e-11e9-9dab-74ad205c0a41.png)

**Comment by mike-u** [comment]
This occurs for me when users specify code syntax without a language attached, like:
'''
code_snippet = function(input)
'''

Would it be possible to make it white text on a black background if no language is selected?
